image: node:22-alpine  # Use Alpine-based image with Node.js 22

stages:
  - install
  - build
  - deploy

variables:
  # Use Node.js version you prefer (make sure to use the right version)
  NODE_VERSION: "22"  

install_dependencies:
  stage: install
  tags: 
   - docker
  script:
    - apk add --no-cache nodejs npm  # Install Node.js and npm in Alpine image
    - cd Client
    - npm install  

build:
  stage: build
  tags: 
   - docker
  script:
    - cd client
    - npm install
    - npm run build  # Build the Vue.js app with Vite

deploy:
  stage: deploy
  tags:
    - docker
  script:
   - cd Client
   - npm install
 
     


