image: node:22-alpine  # Use Alpine-based image with Node.js 22

before_script:
  # Install curl in the alpine-based Docker image
  - apk add --no-cache curl

  # Install Arduino CLI and dependencies
  - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
  - export PATH=$PATH:$HOME/bin

  # Install Seeed Wio Terminal core and libraries
  - arduino-cli core update-index
  - arduino-cli core install Seeeduino:samd
  - arduino-cli lib install "PubSubClient@2.8"
  - arduino-cli lib install "Seeed Arduino rpcWiFi@1.0.7"

stages:
  - install
  - build
  - deploy

variables:
  NODE_VERSION: "22"  

install_dependencies:
  stage: install
  tags: 
   - docker
  script:
    - apk add --no-cache nodejs npm  # Install Node.js and npm in Alpine image
    - cd Client
    - npm install  

build:
  stage: build
  tags: 
   - docker
  script:
    - cd Client
    - npm install
    - npm run build  # Build the Vue.js app with Vite

deploy:
  stage: deploy
  tags:
    - docker
  script:
   - cd Client
   - npm install
 
     


