image: node:22-alpine  # Alpine-based image with Node.js 22

before_script:
  # Install curl in the Alpine-based Docker image
  - apk add --no-cache curl

  # Install Arduino CLI
  - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh

  # Set the correct PATH to include the directory where arduino-cli is installed
  - export PATH=$PATH:/builds/ravisha/RoomCount2nd/bin

  # Verify that Arduino CLI is installed and check the version
  - arduino-cli version

  # Install Seeed Wio Terminal core and libraries
  - arduino-cli core update-index
  - arduino-cli lib install "PubSubClient@2.8"
  - arduino-cli lib install "Seeed Arduino rpcWiFi@1.0.7"

stages:
  - install
  - build
  - deploy

variables:
  NODE_VERSION: "22"  

install_dependencies:
  stage: install
  tags: 
   - docker
  script:
    - apk add --no-cache nodejs npm  # Install Node.js and npm in Alpine image
    - cd Client
    - npm install  

build:
  stage: build
  tags: 
   - docker
  script:
    - cd Client
    - npm install
    - npm run build  # Build the Vue.js app with Vite

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - cd Client
    - npm install
    
    - npm run dev 
 
     


